version: '3.7'
services:
  api:
    command: [ 'sh', '-c', 'yarn api:dev' ]
    depends_on:
      - db
    volumes:
      - ./:/var/www/api

  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db

volumes:
  database:
