version: '3.7'
services:
  api:
    command: ['sh', '-c', 'yarn api']
    depends_on:
      - db
    volumes:
      - ./:/var/www/api

  processor:
    command: ['sh', '-c', 'scripts/wq.sh && yarn processor']
    depends_on:
      - queue
    volumes:
      - ./:/var/www/api

  blockrange:
    command: ['sh', '-c', 'scripts/wq.sh && yarn blockrange']
    depends_on:
      - queue
    volumes:
      - ./:/var/www/api

  filler:
    environment:
      CONFIG: '${CONFIG}'
      FILLER_FLAGS: '-r'
    command:
      ['sh', '-c', 'scripts/wq.sh && flags="${FILLER_FLAGS}" yarn filler -r -s 173000000']
    restart: on-failure
    volumes:
      - eosdac-api:/tmp/
      - ./mainnet.config.js:/var/www/api/mainnet.config.js

  ws:
    command:
      ['sh', '-c', 'yarn ws']
    volumes:
      - ./:/var/www/api

  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db

  queue: # login guest:guest
    image: rabbitmq:management
    hostname: dao-queue
    restart: always
    ulimits:
      nofile:
        soft: 128000
        hard: 128000
    ports:
      #- '5672:5672'
      - '43235:15672'
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbit consumer_timeout 5400000'

volumes:
  database:
