version: '3.7'
services:
  api:
    image: ghcr.io/alien-worlds/eosdac_api
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG: '${CONFIG}'
      cache_from:
        - ghcr.io/alien-worlds/eosdac_api
    environment:
      CONFIG: '${CONFIG}'
      SERVER_PORT: '8800'
      SERVER_ADDR: '0.0.0.0'
    restart: on-failure
    ports:
      - '8800:8800'
    volumes:
      - eosdac-api:/tmp/

networks:
  default:
    external: true
    name: lamington

volumes:
  eosdac-api:
