version: '3.7'
services:
  api:
    image: ghcr.io/alien-worlds/dao_api
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      cache_from:
        - ghcr.io/alien-worlds/dao_api
    environment:
      ENVIRONMENT: '${ENVIRONMENT}'
      SERVER_PORT: '8800'
      SERVER_ADDR: '0.0.0.0'
    restart: on-failure
    ports:
      - '8800:8800'
    volumes:
      - dao-api:/tmp/

networks:
  default:
    external: false
    name: lamington

volumes:
  dao-api:
